# Generated by Django 3.0.5 on 2020-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('c', 'Choice'), ('t', 'Text')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
