# Generated by Django 3.0.5 on 2020-05-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200516_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['pub_date']},
        ),
    ]
