# Generated by Django 3.0.5 on 2020-05-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20200516_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['new_survey_id', 'pub_date']},
        ),
        migrations.AddField(
            model_name='survey',
            name='new_survey_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poll.NewSurvey'),
            preserve_default=False,
        ),
    ]
