# Generated by Django 3.0.5 on 2020-06-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200621_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answer',
            field=models.TextField(max_length=400),
        ),
    ]
